### ISSUE TITLE
Accelerate ggplot2 with canvas

### ISSUE THREAD

**Issue by awunderground** [UrbanInstitute/dynasim-shiny1#6]
Ilya Kashnitsky has a [good blog post](https://ikashnitsky.github.io/2017/ggplot2-microbenchmark/) on how using canvas can accelerate `ggplot2`. This could speed up the application.

**Comment by 5881159** [comment]
What is this?

**Comment by awunderground** [comment]
When I was finishing the applications in July, I thought switching the way the plots were created in `ggplot2` could speed up the application. That theory was based on this [blog post](https://ikashnitsky.github.io/2017/ggplot2-microbenchmark/).

This [blog post](https://www.data-imaginist.com/2017/beneath-the-canvas/) disputes the conclusions of the previous blog post. A `ggplot2` canvas doesn't exist and changing the plotting will create little to no performance gain. 

Ultimately, filtering the data is what takes time and changing the way the data are filtered created big performance gains before publication.
